# Generated by Django 3.2.9 on 2021-11-26 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tire', '0003_alter_usertire_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertire',
            name='tire',
            field=models.ForeignKey(db_column='tire_trim_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_tires', to='tire.tire', to_field='trim_id'),
        ),
        migrations.AlterModelTable(
            name='tire',
            table='tire',
        ),
        migrations.AlterModelTable(
            name='usertire',
            table='user_tire_info',
        ),
    ]
