# Generated by Django 3.2.9 on 2021-11-26 07:03

from django.db import migrations
import django.db.models.deletion
import tire.models


class Migration(migrations.Migration):

    dependencies = [
        ('tire', '0004_auto_20211126_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertire',
            name='tire',
            field=tire.models.NamedForeignKey(db_column='tire_trim_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_tires', to='tire.tire', to_field='trim_id'),
        ),
    ]
